version: "3.7"

services:
  web:
    build: ./social_marks
    # command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./social_marks/:/usr/src/social_marks/
    ports:
      - 8000:8000
    env_file:
      - ./social_marks/.env
    depends_on: 
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminr8ght
      - POSTGRES_DB=social_marks

volumes:
  postgres-data:
